interface Features {
    roleids?: number,
    userManagement_View?: boolean,
    userManagement_create?: boolean,
    userManagement_Update?: boolean,
    userManagement_Delete?: boolean,
    clientManagement_View?: boolean,
    clientManagement_create?: boolean,
    clientManagement_Update?: boolean,
    clientManagement_Delete?: boolean,
    caseManagement_View?: boolean,
    caseManagement_create?: boolean,
    caseManagement_Update?: boolean,
    caseManagement_Delete?: boolean,
    deedManagement_View?: boolean,
    deedManagement_create?: boolean,
    deedManagement_Update?: boolean,
    deedManagement_Delete?: boolean,
    eventManagement_View?: boolean,
    eventManagement_create?: boolean,
    eventManagement_Update?: boolean,
    eventManagement_Delete?: boolean,
    booksManagement_View?: boolean,
    booksManagement_create?: boolean,
    booksManagement_Update?: boolean,
    booksManagement_Delete?: boolean,
    reportManagement_View?: boolean,
    reportManagement_create?: boolean,
    reportManagement_Update?: boolean,
    reportManagement_Delete?: boolean,
    backupManagement_View?: boolean,
    backupManagement_create?: boolean,
    backupManagement_Update?: boolean,
    backupManagement_Delete?: boolean,

}