interface Lawyer {
    id?: number,
    title?: string,
    regno?: number,
    firstname?: string,
    lastname?: string,    
    nic?: string,
    gender?: string,
    birthday?: Date,
    email?: string,
    mobileno?: string,
    address1?: string,
    address2?: string,
    date_joined?: Date,
    experience?: string,   
    practice_area?: string,     
    call_to_bar?: Date,
    qualifications?: string,   
    profile_picture?: any,
    designation?: string,
  }