export interface Staff{
    id: number,
    firstname: string,
    lastname: string,
    address1: string,
    address2: string,
    nic:string,
    title:string,
    mobileno: string,
    email: string,
    birthday: string,
    call_to_bar: string,
    date_joined: string,
    qualifications:string,
    practice_area:string,
    experience: string,
    gender: string,
    designation: string,
}